# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# IMPORTANTE: ESTE ES UN ARCHIVO GENERADO COMO PLANTILLA.
# DEBES REEMPLAZARLO EJECUTANDO EN EL SERVIDOR:
# sudo nixos-generate-config --dir /tmp && cp /tmp/hardware-configuration.nix /path/to/nixos-config/hosts/server/
#
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # Asume intel por defecto, si es AMD será kvm-amd en el archivo final
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/REEMPLAZAR-UUID-RAIZ";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/REEMPLAZAR-UUID-BOOT";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
